### ISSUE TITLE
what's this?

### ISSUE THREAD

**Issue by gaverdugo** [Nifled/tap-universiada#1]

**Comment by gaverdugo** [comment]
<img width="151" alt="captura de pantalla 2018-03-14 a la s 08 10 34" src="https://user-images.githubusercontent.com/7308497/37411072-2aeac226-275f-11e8-955d-baf5530a26fe.png">

**Comment by abrahamhurtado** [comment]
![image](https://user-images.githubusercontent.com/8336082/37411416-fd6b173c-275f-11e8-93b1-0e2809c13810.png)
